modLoader = "javafml"
loaderVersion = "[4,)"
license = "GNU LGPL 3.0"

issueTrackerURL = "https://github.com/hackermdch/MediaPlayer/issues"
[[mods]]
modId = "mediaplayer"
version = "${version}"
displayName = "MediaPlayer"
authors = "hackermdch"
description = '''
play video
'''

[[mixins]]
config = "mediaplayer-common.mixins.json"
[[mixins]]
config = "mediaplayer.mixins.json"

[[dependencies.mediaplayer]]
modId = "forge"
type = "required"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mediaplayer]]
modId = "minecraft"
type = "required"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"

